[package]
authors = ["Ramsay Leung <ramsayleung@gmail.com>"]
name = "rspotify"
version = "0.7.0"
license = "MIT"
readme = "README.md"
description="Spotify API wrapper"
homepage="https://github.com/samrayleung/rspotify"
repository="https://github.com/samrayleung/rspotify"
keywords=["spotify","api"]
[dependencies]
base64 = "0.10.0"
derive_builder = "0.7"
dotenv = "0.13.0"
env_logger = "0.6.0"
itertools = "0.8.0"
log = "0.4"
percent-encoding = "1.0.1"
rand = "0.6.5"
random = "0.12.2"
reqwest = "=0.9.17"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.6.0"
webbrowser = { version = "0.5.2", git = "https://github.com/sabino/webbrowser-rs" }
lazy_static = "1.0"
failure = "0.1"

[dependencies.chrono]
features = ["serde", "rustc-serialize"]
version = "0.4"
